---
# In order for this to work, you have to set the Docker Hub username and
# password:
#
# travis env set DOCKER_USERNAME myusername
# travis env set DOCKER_PASSWORD secretsecret
language: shell

script:
  - docker build . -t esanumeventapp/alpine-pgloader
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push esanumeventapp/alpine-pgloader:latest
